version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_service_app
    ports:
      - "5432:5432"
    volumes:
      - " ./.data/db:/var/lib/postgres"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


networks:
  mindswap-net:
    driver: bridge